rmdir "..\SAPIENT Test Harness BSI Flex 335 v2" /S /Q

mkdir "..\SAPIENT Test Harness BSI Flex 335 v2"
mkdir "..\SAPIENT Test Harness BSI Flex 335 v2\ASM1"
mkdir "..\SAPIENT Test Harness BSI Flex 335 v2\ASM2"
mkdir "..\SAPIENT Test Harness BSI Flex 335 v2\ASM3"
mkdir "..\SAPIENT Test Harness BSI Flex 335 v2\DMM"
mkdir "..\SAPIENT Test Harness BSI Flex 335 v2\ASM1_DataAgent"
mkdir "..\SAPIENT Test Harness BSI Flex 335 v2\ASM2_DataAgent"
mkdir "..\SAPIENT Test Harness BSI Flex 335 v2\ASM3_DataAgent"
mkdir "..\SAPIENT Test Harness BSI Flex 335 v2\DMM_DataAgent"

copy "..\SapientAsmSimulator\SapientAsmSimulator\bin\Release\net6.0-windows\*" "..\SAPIENT Test Harness BSI Flex 335 v2\ASM1\"
copy "..\SapientAsmSimulator\SapientAsmSimulator\bin\Release\net6.0-windows\*" "..\SAPIENT Test Harness BSI Flex 335 v2\ASM2\"
copy "..\SapientAsmSimulator\SapientAsmSimulator\bin\Release\net6.0-windows\*" "..\SAPIENT Test Harness BSI Flex 335 v2\ASM3\"
copy "..\SapientDmmSimulator\SapientDmmSimulator\bin\Release\net6.0-windows\*" "..\SAPIENT Test Harness BSI Flex 335 v2\DMM\"
copy "..\SapientDataAgent\SapientDataAgent\bin\Release\net6.0-windows\*" "..\SAPIENT Test Harness BSI Flex 335 v2\ASM1_DataAgent\"
copy "..\SapientDataAgent\SapientDataAgent\bin\Release\net6.0-windows\*" "..\SAPIENT Test Harness BSI Flex 335 v2\ASM2_DataAgent\"
copy "..\SapientDataAgent\SapientDataAgent\bin\Release\net6.0-windows\*" "..\SAPIENT Test Harness BSI Flex 335 v2\ASM3_DataAgent\"
copy "..\SapientDataAgent\SapientDataAgent\bin\Release\net6.0-windows\*" "..\SAPIENT Test Harness BSI Flex 335 v2\DMM_DataAgent\"
copy ".\Files_ASM1\*" "..\SAPIENT Test Harness BSI Flex 335 v2\ASM1\"
copy ".\Files_ASM2\*" "..\SAPIENT Test Harness BSI Flex 335 v2\ASM2\"
copy ".\Files_ASM3\*" "..\SAPIENT Test Harness BSI Flex 335 v2\ASM3\"
copy ".\Files_DMM\*" "..\SAPIENT Test Harness BSI Flex 335 v2\DMM\"
copy ".\Files_ASMDataAgent1\*" "..\SAPIENT Test Harness BSI Flex 335 v2\ASM1_DataAgent\"
copy ".\Files_ASMDataAgent2\*" "..\SAPIENT Test Harness BSI Flex 335 v2\ASM2_DataAgent\"
copy ".\Files_ASMDataAgent3\*" "..\SAPIENT Test Harness BSI Flex 335 v2\ASM3_DataAgent\"
copy ".\Files_DMMDataAgent\*" "..\SAPIENT Test Harness BSI Flex 335 v2\DMM_DataAgent\"
copy ".\BatchFiles\*" "..\SAPIENT Test Harness BSI Flex 335 v2\"
